# Generated by Django 5.0 on 2023-12-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("futsal_name", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="futsalbookingdetail",
            name="booking_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Booking Date"),
        ),
        migrations.AlterField(
            model_name="futsalbookingdetail",
            name="rate",
            field=models.IntegerField(verbose_name="Rate"),
        ),
    ]
