# Generated by Django 5.0 on 2023-12-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("futsal_name", "0002_alter_futsalbookingdetail_booking_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="futsalbookingdetail",
            name="booking_date",
            field=models.CharField(max_length=50, verbose_name="Booking Date"),
        ),
    ]
