# Generated by Django 5.0 on 2023-12-31 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("futsal_name", "0003_alter_futsalbookingdetail_booking_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="futsalbookingdetail",
            old_name="futsal_name",
            new_name="name",
        ),
    ]
