# Generated by Django 5.0 on 2023-12-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("futsal_name", "0004_rename_futsal_name_futsalbookingdetail_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="futsal_name",
            name="address",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="futsal_name",
            name="name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="futsal_name",
            name="phone",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="futsal_name",
            name="web",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="futsal_name",
            name="zip_code",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="futsalbookingdetail",
            name="booking_date",
            field=models.DateField(verbose_name="Booking Date"),
        ),
        migrations.AlterField(
            model_name="futsalbookinguser",
            name="phone",
            field=models.CharField(max_length=10),
        ),
    ]
