# Generated by Django 5.0 on 2023-12-31 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("futsal_name", "0006_rename_name_futsalbookingdetail_futsal_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Futsal_name",
            new_name="Futsal",
        ),
        migrations.RenameField(
            model_name="futsalbookingdetail",
            old_name="futsal_name",
            new_name="booking_detail",
        ),
        migrations.AlterField(
            model_name="futsalbookingdetail",
            name="booking_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Booking Date"
            ),
        ),
    ]
