# Generated by Django 5.0 on 2023-12-31 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("futsal_name", "0007_rename_futsal_name_futsal_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="futsalbookingdetail",
            old_name="booking_detail",
            new_name="futsal",
        ),
    ]
