# Generated by Django 5.0 on 2024-01-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("futsal_name", "0010_alter_futsalbookingdetail_incharge"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="futsal",
            name="email_adress",
        ),
        migrations.AddField(
            model_name="futsal",
            name="email_address",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
